const $=id=>document.getElementById(id);
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
let accounts=[],account='',folder='inbox',messages=[],epoch=0;
async function api(path,body){const r=await fetch(path,{...(body?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}:{})});const data=await r.json();if(!r.ok)throw new Error(data.error||'The mailbox could not be loaded.');return data;}
const time=value=>{const date=new Date(value);return date.toDateString()===new Date().toDateString()?date.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}):date.toLocaleDateString([],{month:'short',day:'numeric'});};
function list(){const query=$('search').value.trim().toLowerCase(),filtered=messages.filter(m=>[m.Subject,m.From?.Name,m.From?.Address,m.Snippet].join(' ').toLowerCase().includes(query));$('count').textContent=folder==='inbox'?messages.filter(m=>!m.Read).length||'':'';$('messages').innerHTML=filtered.length?filtered.map(m=>`<button class="message ${m.Read?'':'unread'}" data-id="${escapeHtml(m.ID)}"><span class="sender-avatar">${escapeHtml((m.From?.Name||m.From?.Address||'?')[0].toUpperCase())}</span><span class="sender">${escapeHtml(folder==='sent'?(m.To?.[0]?.Name||m.To?.[0]?.Address):m.From?.Name||m.From?.Address)}</span><span class="preview"><span class="subject">${escapeHtml(m.Subject||'(no subject)')}</span><span class="snippet"> — ${escapeHtml(m.Snippet||'')}</span></span><span class="date">${escapeHtml(time(m.Created))}</span></button>`).join(''):'<div class="empty"><h2>All clear.</h2><p>Your messages will appear here.</p></div>';document.querySelectorAll('[data-id]').forEach(button=>button.onclick=()=>void openMessage(button.dataset.id));}
async function refresh(){const current=++epoch,owner=account;try{const data=await api(`/api/messages?account=${encodeURIComponent(owner)}&folder=${folder}`);if(current!==epoch)return;messages=data.messages;$('status').textContent='';list();}catch(e){if(current===epoch)$('status').textContent=e.message;}}
function mailbox(){$('reader').hidden=true;$('messages').hidden=false;$('heading').textContent=folder==='inbox'?'Inbox':'Sent';document.querySelectorAll('.folder').forEach(b=>b.classList.toggle('selected',b.dataset.folder===folder));void refresh();}
function linkedText(text){return String(text||'').split(/(https?:\/\/[^\s<>]+)/g).map(part=>{if(!/^https?:\/\//.test(part))return escapeHtml(part);try{const u=new URL(part);if(!['http:','https:'].includes(u.protocol))return escapeHtml(part);return `<a href="${escapeHtml(u.href)}" target="_blank" rel="noopener noreferrer">${escapeHtml(part)}</a>`;}catch{return escapeHtml(part);}}).join('');}
async function openMessage(id){const owner=account;try{const m=await api(`/api/message/${encodeURIComponent(id)}`);if(owner!==account)return;$('messages').hidden=true;$('reader').hidden=false;$('reader').innerHTML=`<button class="back" id="back">← Back to ${folder==='inbox'?'inbox':'sent'}</button><h2>${escapeHtml(m.Subject||'(no subject)')}</h2><div class="message-meta"><span class="sender-avatar">${escapeHtml((m.From?.Name||m.From?.Address||'?')[0].toUpperCase())}</span><div><strong>${escapeHtml(m.From?.Name||m.From?.Address)}</strong> &lt;${escapeHtml(m.From?.Address)}&gt;<br>to ${escapeHtml((m.To||[]).map(to=>to.Address).join(', '))}</div><time>${escapeHtml(new Date(m.Date||m.Created).toLocaleString())}</time></div><div class="mail-body">${linkedText(m.Text||'This message contains no plain-text version. Open the Mailpit inspector to view the original MIME content.')}</div><button class="reply" id="reply">↩ Reply</button>`;$('back').onclick=mailbox;$('reply').onclick=()=>compose(m);void refresh();}catch(e){$('status').textContent=e.message;}}
function compose(reply){$('from').value=account;$('to').value=reply?.From?.Address?.endsWith('@demo.test')?reply.From.Address:'';$('subject').value=reply?(/^Re:/i.test(reply.Subject)?reply.Subject:`Re: ${reply.Subject}`):'';$('body').value='';$('send-error').textContent='';$('composer').showModal();(reply?$('body'):$('to')).focus();}
$('compose').onclick=()=>compose();$('close-compose').onclick=()=>$('composer').close();$('refresh').onclick=()=>void refresh();$('search').oninput=list;
document.querySelectorAll('.folder').forEach(b=>b.onclick=()=>{folder=b.dataset.folder;mailbox();});
$('account').onchange=()=>{account=$('account').value;const current=accounts.find(a=>a.email===account);$('avatar').textContent=current.name[0];$('account-name').textContent=current.name;$('account-address').textContent=current.email;$('search').value='';folder='inbox';mailbox();};
$('send-form').onsubmit=async event=>{event.preventDefault();$('send').disabled=true;$('send').textContent='Sending…';$('send-error').textContent='';try{await api('/api/send',{from:account,to:$('to').value.trim(),subject:$('subject').value,text:$('body').value});$('composer').close();folder='sent';mailbox();}catch(e){$('send-error').textContent=e.message;}finally{$('send').disabled=false;$('send').textContent='Send ↗';}};
void(async()=>{try{accounts=await api('/api/accounts');$('account').innerHTML=accounts.map(a=>`<option value="${escapeHtml(a.email)}">${escapeHtml(a.name)} · ${escapeHtml(a.email)}</option>`).join('');$('recipients').innerHTML=accounts.map(a=>`<option value="${escapeHtml(a.email)}">${escapeHtml(a.name)}</option>`).join('');$('account').onchange();setInterval(()=>{if(!document.hidden)void refresh();},3000);}catch(e){$('status').textContent=e.message;}})();
