import type { FastifyInstance } from "fastify";

/** A fixed-width viewport of the actual Expo app, with its own session. */
export function registerMobilePreview(app: FastifyInstance, appOrigin: string) {
  const source = new URL(appOrigin).origin.replace(/&/g, "&amp;").replace(/"/g, "&quot;");
  app.get("/mobile-preview", async (_request, reply) => reply.type("text/html").send(`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Fantasy Phishing · Phone preview</title>
<style>*{box-sizing:border-box}body{margin:0;background:#080C12;color:#F5F7FA;font:14px system-ui;min-height:100vh;display:grid;grid-template-columns:1fr 430px 1fr;align-items:center;gap:32px;padding:36px}aside{max-width:280px;justify-self:end}h1{font-size:38px;line-height:1.05;letter-spacing:-1.5px;margin:18px 0}p{color:#99A5B8;line-height:1.65}.tag{font-size:10px;letter-spacing:2px;color:#BBF451;font-weight:800}a{color:#BBF451}button{font:inherit;background:#151E2B;color:#F5F7FA;border:1px solid #303E50;border-radius:8px;padding:10px 14px;cursor:pointer;margin:0 4px 12px 0}button[aria-pressed=true]{color:#BBF451;border-color:#BBF451}.device{width:414px;max-width:100%;border:2px solid #334052;border-radius:46px;background:#0B1018;padding:10px;box-shadow:0 28px 100px #0009;transition:width .2s}.viewport{position:relative;overflow:hidden;border-radius:35px;height:min(844px,85vh);min-height:580px}iframe{width:100%;height:100%;border:0;background:#0B1018}footer{font-size:11px;color:#768298;text-align:center;line-height:1.7;margin-top:16px}.phone-area{display:flex;align-items:center;flex-direction:column;max-width:430px}@media(max-width:1000px){body{grid-template-columns:1fr;justify-items:center;padding:20px}aside{justify-self:center;text-align:center;max-width:440px}h1{font-size:28px;margin:8px 0}aside p{margin:8px 0}.viewport{height:780px}body>div:last-child{display:none}}@media(max-width:440px){body{padding:10px}.device{width:100%;padding:5px;border-radius:28px}.viewport{border-radius:23px}}
</style></head><body><aside><span class="tag">FANTASY PHISHING / MOBILE</span><h1>Your league.<br>In your pocket.</h1><p>This is the interactive mobile layout of the app. Click, type, scroll, and switch accounts just as you would on your phone.</p><div aria-label="Preview size"><button id="compact" aria-pressed="false">Compact</button><button id="large" aria-pressed="true">Large</button></div><p><a href="${source}" target="_blank" rel="noopener">Open desktop app ↗</a></p><p style="font-size:12px">This browser preview runs the shared React Native web app. Native iOS testing uses Xcode’s iPhone Simulator.</p></aside><section class="phone-area"><div class="device" id="device"><div class="viewport"><iframe title="Interactive Fantasy Phishing mobile app" src="${source}/" allow="autoplay; fullscreen; clipboard-write"></iframe></div></div><footer>LIVE APP · TOUCH LAYOUT<br>Use your mouse or trackpad to scroll inside the phone.</footer></section><div></div><script>const device=document.getElementById('device');for(const id of ['compact','large'])document.getElementById(id).onclick=()=>{device.style.width=id==='compact'?'375px':'414px';for(const other of ['compact','large'])document.getElementById(other).setAttribute('aria-pressed',String(id===other));};</script></body></html>`));
}
